# general info
name: ZeroDCE_Train_LOL_Eval_LOL
notes: ""

# model
model: 
  name: zero_dce
  scale_factor: 1

# loss
loss:
  # weights for different loss components
  W_L2: 0                               # L2 loss (nn.MSELoss)
  W_L1: 1                               # L1 loss (nn.SmoothL1Loss)
  W_TV: 0                               # Total Variation Loss
  W_col: 0                              # Color Consistency Loss
  W_spa: 0                              # Spatial Consistency Loss
  W_exp: 0                              # Exposure Control Loss
  patch_size: 0                         # - patch size for exposure control loss
  E: 0                                  # - exposure level for exposure control loss
  W_cos: 0                              # Color Angle Loss


# dataset
dataset: LOL                            # now supports [LOL, VELOL, SICE, FiveK]
data_dir: /home/ppnk-wsl/capstone/Dataset/LOL/
augment: False                          # augment training set if enabled
resize: null                            # input & target resize if specified
low_res: null
num_workers: 4                          # num_workers used in DataLoader

# train
lr: 1e-4                                # learning rate
bs: 8                                   # batch size
weight_decay: 0                         # weight decay
epochs: 100                             # number of training epochs
resume_from: null                       # resume pretrained model from this path
checkpoint_save_path: ./result/checkpoints/       # save checkpoint to {name}/ under this directory
visualization_save_path: ./result/visualization/  # save visualization to {name}/ under this directory

# eval
eval_model_path: null                   # checkpoint used for evaluation (test.py)

# misc
tensorboard: False                      # run "tensorboard --logdir runs/"
visualize_interval: 1                   # interval in terms of epochs to save visualization result, null == don't visualize
checkpoint_interval: 1                  # interval in terms of epochs to save model weights, null == don't save
device: null                            # choose from [cpu, cuda], null==use gpu if available if not cpu
profiling: True                         # if enabled, profile network performance on testing only
seed: 0                                 # for repeatability

